webtalk_init -webtalk_dir /home/saba/Documents/Vivado/Final_Project.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-11-28 05:20:28" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211236389_1777520198_0_029" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "op5h8h4e2vmhb0v5vbgrikjv72" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "9" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2693.860 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.170 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1543401350000" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key hwid -value "1543386123000" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key bspid -value "1543389471000" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1543401350000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key DebugCount -value "29" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1543411228790"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1543411228790"
webtalk_transmit -clientid 630679467 -regid "211236389_1777520198_0_029" -xml /home/saba/Documents/Vivado/Final_Project.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/saba/Documents/Vivado/Final_Project.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/saba/Documents/Vivado/Final_Project.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
