# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Public/Vivado/SideServos/SideServos.srcs/sources_1/bd/SideServos/ip/SideServos_processing_system7_0_1/SideServos_processing_system7_0_1.xci
# IP: The module: 'SideServos_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Vivado/SideServos/SideServos.srcs/sources_1/bd/SideServos/ip/SideServos_processing_system7_0_1/SideServos_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'SideServos_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Public/Vivado/SideServos/SideServos.srcs/sources_1/bd/SideServos/ip/SideServos_processing_system7_0_1/SideServos_processing_system7_0_1.xci
# IP: The module: 'SideServos_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Vivado/SideServos/SideServos.srcs/sources_1/bd/SideServos/ip/SideServos_processing_system7_0_1/SideServos_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'SideServos_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
