# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/sensor_reading.xdc

# Block Designs: bd/sensor_reading/sensor_reading.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_reading || ORIG_REF_NAME==sensor_reading} -quiet] -quiet

# IP: bd/sensor_reading/ip/sensor_reading_processing_system7_0_0/sensor_reading_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_reading_processing_system7_0_0 || ORIG_REF_NAME==sensor_reading_processing_system7_0_0} -quiet] -quiet

# IP: bd/sensor_reading/ip/sensor_reading_ps7_0_axi_periph_0/sensor_reading_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_reading_ps7_0_axi_periph_0 || ORIG_REF_NAME==sensor_reading_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/sensor_reading/ip/sensor_reading_rst_ps7_0_100M_0/sensor_reading_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_reading_rst_ps7_0_100M_0 || ORIG_REF_NAME==sensor_reading_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sensor_reading/ip/sensor_reading_sensor_readings_0_1/sensor_reading_sensor_readings_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_reading_sensor_readings_0_1 || ORIG_REF_NAME==sensor_reading_sensor_readings_0_1} -quiet] -quiet

# IP: bd/sensor_reading/ip/sensor_reading_auto_pc_0/sensor_reading_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sensor_reading_auto_pc_0 || ORIG_REF_NAME==sensor_reading_auto_pc_0} -quiet] -quiet

# XDC: bd/sensor_reading/sensor_reading_ooc.xdc
