# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Andrew Zaragoza/OneDrive/Desktop/middle_servo-master/middle_servo-master/servo_middle.srcs/constrs_1/imports/Desktop/zedboard_master_XDC_RevC_D_v3.xdc

# Block Designs: bd/MiddleServo/MiddleServo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MiddleServo || ORIG_REF_NAME==MiddleServo} -quiet] -quiet

# IP: bd/MiddleServo/ip/MiddleServo_processing_system7_0_0/MiddleServo_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MiddleServo_processing_system7_0_0 || ORIG_REF_NAME==MiddleServo_processing_system7_0_0} -quiet] -quiet

# IP: bd/MiddleServo/ip/MiddleServo_MiddleServo_0_0/MiddleServo_MiddleServo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MiddleServo_MiddleServo_0_0 || ORIG_REF_NAME==MiddleServo_MiddleServo_0_0} -quiet] -quiet

# IP: bd/MiddleServo/ip/MiddleServo_ps7_0_axi_periph_0/MiddleServo_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MiddleServo_ps7_0_axi_periph_0 || ORIG_REF_NAME==MiddleServo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MiddleServo/ip/MiddleServo_rst_ps7_0_50M_0/MiddleServo_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MiddleServo_rst_ps7_0_50M_0 || ORIG_REF_NAME==MiddleServo_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/MiddleServo/ip/MiddleServo_auto_pc_0/MiddleServo_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MiddleServo_auto_pc_0 || ORIG_REF_NAME==MiddleServo_auto_pc_0} -quiet] -quiet

# XDC: bd/MiddleServo/MiddleServo_ooc.xdc
