# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Final.xdc

# Block Designs: bd/Sensor_Project/Sensor_Project.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project || ORIG_REF_NAME==Sensor_Project} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_processing_system7_0_1/Sensor_Project_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_processing_system7_0_1 || ORIG_REF_NAME==Sensor_Project_processing_system7_0_1} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_MiddleServo_0_0/Sensor_Project_MiddleServo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_MiddleServo_0_0 || ORIG_REF_NAME==Sensor_Project_MiddleServo_0_0} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_SideServos_0_0/Sensor_Project_SideServos_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_SideServos_0_0 || ORIG_REF_NAME==Sensor_Project_SideServos_0_0} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_sensor_readings_0_0/Sensor_Project_sensor_readings_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_sensor_readings_0_0 || ORIG_REF_NAME==Sensor_Project_sensor_readings_0_0} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_ps7_0_axi_periph_0/Sensor_Project_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_ps7_0_axi_periph_0 || ORIG_REF_NAME==Sensor_Project_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_rst_ps7_0_100M_0/Sensor_Project_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_rst_ps7_0_100M_0 || ORIG_REF_NAME==Sensor_Project_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_xbar_0/Sensor_Project_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_xbar_0 || ORIG_REF_NAME==Sensor_Project_xbar_0} -quiet] -quiet

# IP: bd/Sensor_Project/ip/Sensor_Project_auto_pc_0/Sensor_Project_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sensor_Project_auto_pc_0 || ORIG_REF_NAME==Sensor_Project_auto_pc_0} -quiet] -quiet

# XDC: bd/Sensor_Project/Sensor_Project_ooc.xdc
