# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Public/Vivado/Final_Project.srcs/sources_1/bd/Sensor_Project/ip/Sensor_Project_xbar_0/Sensor_Project_xbar_0.xci
# IP: The module: 'Sensor_Project_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Vivado/Final_Project.srcs/sources_1/bd/Sensor_Project/ip/Sensor_Project_xbar_0/Sensor_Project_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensor_Project_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Public/Vivado/Final_Project.srcs/sources_1/bd/Sensor_Project/ip/Sensor_Project_xbar_0/Sensor_Project_xbar_0.xci
# IP: The module: 'Sensor_Project_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Public/Vivado/Final_Project.srcs/sources_1/bd/Sensor_Project/ip/Sensor_Project_xbar_0/Sensor_Project_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Sensor_Project_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
