# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Andrew Zaragoza/OneDrive/Desktop/side_servos-master/side_servos-master/servos_new.srcs/constrs_1/imports/Desktop/zedboard_master_XDC_RevC_D_v3.xdc

# Block Designs: bd/SideServos/SideServos.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SideServos || ORIG_REF_NAME==SideServos} -quiet] -quiet

# IP: bd/SideServos/ip/SideServos_processing_system7_0_1/SideServos_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SideServos_processing_system7_0_1 || ORIG_REF_NAME==SideServos_processing_system7_0_1} -quiet] -quiet

# IP: bd/SideServos/ip/SideServos_SideServos_0_0/SideServos_SideServos_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SideServos_SideServos_0_0 || ORIG_REF_NAME==SideServos_SideServos_0_0} -quiet] -quiet

# IP: bd/SideServos/ip/SideServos_ps7_0_axi_periph_1/SideServos_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SideServos_ps7_0_axi_periph_1 || ORIG_REF_NAME==SideServos_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/SideServos/ip/SideServos_rst_ps7_0_100M_1/SideServos_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SideServos_rst_ps7_0_100M_1 || ORIG_REF_NAME==SideServos_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/SideServos/ip/SideServos_auto_pc_0/SideServos_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==SideServos_auto_pc_0 || ORIG_REF_NAME==SideServos_auto_pc_0} -quiet] -quiet

# XDC: bd/SideServos/SideServos_ooc.xdc
